Using Rs CFLAGS and LDFLAGS

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2104,6 +2104,17 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+# Check the compiler configured with R
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+LDFLAGS=`"${R_HOME}/bin/R" CMD config LDFLAGS`
+
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
